//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 22/03/2015 12:18:33
namespace TreatiesService.Service
{
    
    /// <summary>
    /// There are no comments for TreatyProfileContext in the schema.
    /// </summary>
    public partial class TreatyProfileContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TreatyProfileContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TreatyProfileContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "CountryProfiles", "TreatiesService.Service");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "brsWsCore", "TreatiesService.Service.brsWsCore");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TreatiesService.Service.brsWsCore", global::System.StringComparison.Ordinal))
            {
                return string.Concat("brsWsCore.", clientType.Name);
            }
            if (clientType.Namespace.Equals("TreatiesService.Service", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CountryProfiles.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TreatyProfiles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TreatyProfile> TreatyProfiles
        {
            get
            {
                if ((this._TreatyProfiles == null))
                {
                    this._TreatyProfiles = base.CreateQuery<TreatyProfile>("TreatyProfiles");
                }
                return this._TreatyProfiles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TreatyProfile> _TreatyProfiles;
        /// <summary>
        /// There are no comments for EndorsmentDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EndorsmentDetails> EndorsmentDetails
        {
            get
            {
                if ((this._EndorsmentDetails == null))
                {
                    this._EndorsmentDetails = base.CreateQuery<EndorsmentDetails>("EndorsmentDetails");
                }
                return this._EndorsmentDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EndorsmentDetails> _EndorsmentDetails;
        /// <summary>
        /// There are no comments for countryNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TreatiesService.Service.brsWsCore.brsCountryName> countryNames
        {
            get
            {
                if ((this._countryNames == null))
                {
                    this._countryNames = base.CreateQuery<TreatiesService.Service.brsWsCore.brsCountryName>("countryNames");
                }
                return this._countryNames;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TreatiesService.Service.brsWsCore.brsCountryName> _countryNames;
        /// <summary>
        /// There are no comments for TreatiesInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TreatyInfo> TreatiesInfo
        {
            get
            {
                if ((this._TreatiesInfo == null))
                {
                    this._TreatiesInfo = base.CreateQuery<TreatyInfo>("TreatiesInfo");
                }
                return this._TreatiesInfo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TreatyInfo> _TreatiesInfo;
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TreatyNote> Notes
        {
            get
            {
                if ((this._Notes == null))
                {
                    this._Notes = base.CreateQuery<TreatyNote>("Notes");
                }
                return this._Notes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TreatyNote> _Notes;
        /// <summary>
        /// There are no comments for TreatyProfiles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTreatyProfiles(TreatyProfile treatyProfile)
        {
            base.AddObject("TreatyProfiles", treatyProfile);
        }
        /// <summary>
        /// There are no comments for EndorsmentDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEndorsmentDetails(EndorsmentDetails endorsmentDetails)
        {
            base.AddObject("EndorsmentDetails", endorsmentDetails);
        }
        /// <summary>
        /// There are no comments for countryNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTocountryNames(TreatiesService.Service.brsWsCore.brsCountryName brsCountryName)
        {
            base.AddObject("countryNames", brsCountryName);
        }
        /// <summary>
        /// There are no comments for TreatiesInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTreatiesInfo(TreatyInfo treatyInfo)
        {
            base.AddObject("TreatiesInfo", treatyInfo);
        }
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNotes(TreatyNote treatyNote)
        {
            base.AddObject("Notes", treatyNote);
        }
    }
    /// <summary>
    /// There are no comments for CountryProfiles.TreatyProfile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TreatyProfiles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class TreatyProfile : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TreatyProfile object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="protocolVersion">Initial value of protocolVersion.</param>
        /// <param name="updated">Initial value of updated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TreatyProfile CreateTreatyProfile(string ID, int protocolVersion, global::System.DateTime updated)
        {
            TreatyProfile treatyProfile = new TreatyProfile();
            treatyProfile.id = ID;
            treatyProfile.protocolVersion = protocolVersion;
            treatyProfile.updated = updated;
            return treatyProfile;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _id;
        partial void OnidChanging(string value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property protocolVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int protocolVersion
        {
            get
            {
                return this._protocolVersion;
            }
            set
            {
                this.OnprotocolVersionChanging(value);
                this._protocolVersion = value;
                this.OnprotocolVersionChanged();
                this.OnPropertyChanged("protocolVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _protocolVersion;
        partial void OnprotocolVersionChanging(int value);
        partial void OnprotocolVersionChanged();
        /// <summary>
        /// There are no comments for Property updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime updated
        {
            get
            {
                return this._updated;
            }
            set
            {
                this.OnupdatedChanging(value);
                this._updated = value;
                this.OnupdatedChanged();
                this.OnPropertyChanged("updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _updated;
        partial void OnupdatedChanging(global::System.DateTime value);
        partial void OnupdatedChanged();
        /// <summary>
        /// There are no comments for Property treaty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string treaty
        {
            get
            {
                return this._treaty;
            }
            set
            {
                this.OntreatyChanging(value);
                this._treaty = value;
                this.OntreatyChanged();
                this.OnPropertyChanged("treaty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _treaty;
        partial void OntreatyChanging(string value);
        partial void OntreatyChanged();
        /// <summary>
        /// There are no comments for Property country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string country
        {
            get
            {
                return this._country;
            }
            set
            {
                this.OncountryChanging(value);
                this._country = value;
                this.OncountryChanged();
                this.OnPropertyChanged("country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _country;
        partial void OncountryChanging(string value);
        partial void OncountryChanged();
        /// <summary>
        /// There are no comments for Property FullCountryNameEn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullCountryNameEn
        {
            get
            {
                return this._FullCountryNameEn;
            }
            set
            {
                this.OnFullCountryNameEnChanging(value);
                this._FullCountryNameEn = value;
                this.OnFullCountryNameEnChanged();
                this.OnPropertyChanged("FullCountryNameEn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullCountryNameEn;
        partial void OnFullCountryNameEnChanging(string value);
        partial void OnFullCountryNameEnChanged();
        /// <summary>
        /// There are no comments for Property legalInstrumentName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string legalInstrumentName
        {
            get
            {
                return this._legalInstrumentName;
            }
            set
            {
                this.OnlegalInstrumentNameChanging(value);
                this._legalInstrumentName = value;
                this.OnlegalInstrumentNameChanged();
                this.OnPropertyChanged("legalInstrumentName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _legalInstrumentName;
        partial void OnlegalInstrumentNameChanging(string value);
        partial void OnlegalInstrumentNameChanged();
        /// <summary>
        /// There are no comments for Property legalInstrumentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string legalInstrumentType
        {
            get
            {
                return this._legalInstrumentType;
            }
            set
            {
                this.OnlegalInstrumentTypeChanging(value);
                this._legalInstrumentType = value;
                this.OnlegalInstrumentTypeChanged();
                this.OnPropertyChanged("legalInstrumentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _legalInstrumentType;
        partial void OnlegalInstrumentTypeChanging(string value);
        partial void OnlegalInstrumentTypeChanged();
        /// <summary>
        /// There are no comments for Property parentLegalInstrument in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string parentLegalInstrument
        {
            get
            {
                return this._parentLegalInstrument;
            }
            set
            {
                this.OnparentLegalInstrumentChanging(value);
                this._parentLegalInstrument = value;
                this.OnparentLegalInstrumentChanged();
                this.OnPropertyChanged("parentLegalInstrument");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _parentLegalInstrument;
        partial void OnparentLegalInstrumentChanging(string value);
        partial void OnparentLegalInstrumentChanged();
        /// <summary>
        /// There are no comments for endorsmentDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EndorsmentDetails> endorsmentDetails
        {
            get
            {
                return this._endorsmentDetails;
            }
            set
            {
                this._endorsmentDetails = value;
                this.OnPropertyChanged("endorsmentDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EndorsmentDetails> _endorsmentDetails = new global::System.Data.Services.Client.DataServiceCollection<EndorsmentDetails>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CountryProfiles.EndorsmentDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// endorsmentId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EndorsmentDetails")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("endorsmentId")]
    public partial class EndorsmentDetails : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EndorsmentDetails object.
        /// </summary>
        /// <param name="endorsmentId">Initial value of endorsmentId.</param>
        /// <param name="endorsmentDate">Initial value of endorsmentDate.</param>
        /// <param name="hasEnteredIntoForce">Initial value of hasEnteredIntoForce.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EndorsmentDetails CreateEndorsmentDetails(string endorsmentId, global::System.DateTime endorsmentDate, bool hasEnteredIntoForce)
        {
            EndorsmentDetails endorsmentDetails = new EndorsmentDetails();
            endorsmentDetails.endorsmentId = endorsmentId;
            endorsmentDetails.endorsmentDate = endorsmentDate;
            endorsmentDetails.hasEnteredIntoForce = hasEnteredIntoForce;
            return endorsmentDetails;
        }
        /// <summary>
        /// There are no comments for Property endorsmentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string endorsmentId
        {
            get
            {
                return this._endorsmentId;
            }
            set
            {
                this.OnendorsmentIdChanging(value);
                this._endorsmentId = value;
                this.OnendorsmentIdChanged();
                this.OnPropertyChanged("endorsmentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _endorsmentId;
        partial void OnendorsmentIdChanging(string value);
        partial void OnendorsmentIdChanged();
        /// <summary>
        /// There are no comments for Property endorsmentDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime endorsmentDate
        {
            get
            {
                return this._endorsmentDate;
            }
            set
            {
                this.OnendorsmentDateChanging(value);
                this._endorsmentDate = value;
                this.OnendorsmentDateChanged();
                this.OnPropertyChanged("endorsmentDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _endorsmentDate;
        partial void OnendorsmentDateChanging(global::System.DateTime value);
        partial void OnendorsmentDateChanged();
        /// <summary>
        /// There are no comments for Property dateQualifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string dateQualifier
        {
            get
            {
                return this._dateQualifier;
            }
            set
            {
                this.OndateQualifierChanging(value);
                this._dateQualifier = value;
                this.OndateQualifierChanged();
                this.OnPropertyChanged("dateQualifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _dateQualifier;
        partial void OndateQualifierChanging(string value);
        partial void OndateQualifierChanged();
        /// <summary>
        /// There are no comments for Property declarations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string declarations
        {
            get
            {
                return this._declarations;
            }
            set
            {
                this.OndeclarationsChanging(value);
                this._declarations = value;
                this.OndeclarationsChanged();
                this.OnPropertyChanged("declarations");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _declarations;
        partial void OndeclarationsChanging(string value);
        partial void OndeclarationsChanged();
        /// <summary>
        /// There are no comments for Property objections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string objections
        {
            get
            {
                return this._objections;
            }
            set
            {
                this.OnobjectionsChanging(value);
                this._objections = value;
                this.OnobjectionsChanged();
                this.OnPropertyChanged("objections");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _objections;
        partial void OnobjectionsChanging(string value);
        partial void OnobjectionsChanged();
        /// <summary>
        /// There are no comments for Property notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this.OnnotesChanging(value);
                this._notes = value;
                this.OnnotesChanged();
                this.OnPropertyChanged("notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _notes;
        partial void OnnotesChanging(string value);
        partial void OnnotesChanged();
        /// <summary>
        /// There are no comments for Property hasEnteredIntoForce in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool hasEnteredIntoForce
        {
            get
            {
                return this._hasEnteredIntoForce;
            }
            set
            {
                this.OnhasEnteredIntoForceChanging(value);
                this._hasEnteredIntoForce = value;
                this.OnhasEnteredIntoForceChanged();
                this.OnPropertyChanged("hasEnteredIntoForce");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _hasEnteredIntoForce;
        partial void OnhasEnteredIntoForceChanging(bool value);
        partial void OnhasEnteredIntoForceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CountryProfiles.TreatyInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TreatiesInfo")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class TreatyInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TreatyInfo object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="dateAdoption">Initial value of dateAdoption.</param>
        /// <param name="dateSignature">Initial value of dateSignature.</param>
        /// <param name="dateEntryIntoForce">Initial value of dateEntryIntoForce.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TreatyInfo CreateTreatyInfo(string ID, global::System.DateTime dateAdoption, global::System.DateTime dateSignature, global::System.DateTime dateEntryIntoForce)
        {
            TreatyInfo treatyInfo = new TreatyInfo();
            treatyInfo.id = ID;
            treatyInfo.dateAdoption = dateAdoption;
            treatyInfo.dateSignature = dateSignature;
            treatyInfo.dateEntryIntoForce = dateEntryIntoForce;
            return treatyInfo;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _id;
        partial void OnidChanging(string value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property shortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string shortName
        {
            get
            {
                return this._shortName;
            }
            set
            {
                this.OnshortNameChanging(value);
                this._shortName = value;
                this.OnshortNameChanged();
                this.OnPropertyChanged("shortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _shortName;
        partial void OnshortNameChanging(string value);
        partial void OnshortNameChanged();
        /// <summary>
        /// There are no comments for Property fullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string fullName
        {
            get
            {
                return this._fullName;
            }
            set
            {
                this.OnfullNameChanging(value);
                this._fullName = value;
                this.OnfullNameChanged();
                this.OnPropertyChanged("fullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _fullName;
        partial void OnfullNameChanging(string value);
        partial void OnfullNameChanged();
        /// <summary>
        /// There are no comments for Property cityOfAdoption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string cityOfAdoption
        {
            get
            {
                return this._cityOfAdoption;
            }
            set
            {
                this.OncityOfAdoptionChanging(value);
                this._cityOfAdoption = value;
                this.OncityOfAdoptionChanged();
                this.OnPropertyChanged("cityOfAdoption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _cityOfAdoption;
        partial void OncityOfAdoptionChanging(string value);
        partial void OncityOfAdoptionChanged();
        /// <summary>
        /// There are no comments for Property dateAdoption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateAdoption
        {
            get
            {
                return this._dateAdoption;
            }
            set
            {
                this.OndateAdoptionChanging(value);
                this._dateAdoption = value;
                this.OndateAdoptionChanged();
                this.OnPropertyChanged("dateAdoption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateAdoption;
        partial void OndateAdoptionChanging(global::System.DateTime value);
        partial void OndateAdoptionChanged();
        /// <summary>
        /// There are no comments for Property dateSignature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateSignature
        {
            get
            {
                return this._dateSignature;
            }
            set
            {
                this.OndateSignatureChanging(value);
                this._dateSignature = value;
                this.OndateSignatureChanged();
                this.OnPropertyChanged("dateSignature");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateSignature;
        partial void OndateSignatureChanging(global::System.DateTime value);
        partial void OndateSignatureChanged();
        /// <summary>
        /// There are no comments for Property dateEntryIntoForce in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateEntryIntoForce
        {
            get
            {
                return this._dateEntryIntoForce;
            }
            set
            {
                this.OndateEntryIntoForceChanging(value);
                this._dateEntryIntoForce = value;
                this.OndateEntryIntoForceChanged();
                this.OnPropertyChanged("dateEntryIntoForce");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateEntryIntoForce;
        partial void OndateEntryIntoForceChanging(global::System.DateTime value);
        partial void OndateEntryIntoForceChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<TreatyNote> notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this._notes = value;
                this.OnPropertyChanged("notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<TreatyNote> _notes = new global::System.Data.Services.Client.DataServiceCollection<TreatyNote>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for members in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<TreatyProfile> members
        {
            get
            {
                return this._members;
            }
            set
            {
                this._members = value;
                this.OnPropertyChanged("members");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<TreatyProfile> _members = new global::System.Data.Services.Client.DataServiceCollection<TreatyProfile>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CountryProfiles.TreatyNote in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Notes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class TreatyNote : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TreatyNote object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="order">Initial value of order.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TreatyNote CreateTreatyNote(int ID, int order)
        {
            TreatyNote treatyNote = new TreatyNote();
            treatyNote.id = ID;
            treatyNote.order = order;
            return treatyNote;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property treatyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string treatyId
        {
            get
            {
                return this._treatyId;
            }
            set
            {
                this.OntreatyIdChanging(value);
                this._treatyId = value;
                this.OntreatyIdChanged();
                this.OnPropertyChanged("treatyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _treatyId;
        partial void OntreatyIdChanging(string value);
        partial void OntreatyIdChanged();
        /// <summary>
        /// There are no comments for Property order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int order
        {
            get
            {
                return this._order;
            }
            set
            {
                this.OnorderChanging(value);
                this._order = value;
                this.OnorderChanged();
                this.OnPropertyChanged("order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _order;
        partial void OnorderChanging(int value);
        partial void OnorderChanged();
        /// <summary>
        /// There are no comments for Property text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string text
        {
            get
            {
                return this._text;
            }
            set
            {
                this.OntextChanging(value);
                this._text = value;
                this.OntextChanged();
                this.OnPropertyChanged("text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _text;
        partial void OntextChanging(string value);
        partial void OntextChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name:
// Generation date: 22/03/2015 12:18:33
namespace TreatiesService.Service.brsWsCore
{
    
    /// <summary>
    /// There are no comments for brsWsCore.brsCountryName in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IsoCode2d
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("countryNames")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IsoCode2d")]
    public partial class brsCountryName : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new brsCountryName object.
        /// </summary>
        /// <param name="isoCode2d">Initial value of IsoCode2d.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static brsCountryName CreatebrsCountryName(string isoCode2d)
        {
            brsCountryName brsCountryName = new brsCountryName();
            brsCountryName.IsoCode2d = isoCode2d;
            return brsCountryName;
        }
        /// <summary>
        /// There are no comments for Property IsoCode2d in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IsoCode2d
        {
            get
            {
                return this._IsoCode2d;
            }
            set
            {
                this.OnIsoCode2dChanging(value);
                this._IsoCode2d = value;
                this.OnIsoCode2dChanged();
                this.OnPropertyChanged("IsoCode2d");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IsoCode2d;
        partial void OnIsoCode2dChanging(string value);
        partial void OnIsoCode2dChanged();
        /// <summary>
        /// There are no comments for Property NameEn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NameEn
        {
            get
            {
                return this._NameEn;
            }
            set
            {
                this.OnNameEnChanging(value);
                this._NameEn = value;
                this.OnNameEnChanged();
                this.OnPropertyChanged("NameEn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NameEn;
        partial void OnNameEnChanging(string value);
        partial void OnNameEnChanged();
        /// <summary>
        /// There are no comments for Property NameFr in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NameFr
        {
            get
            {
                return this._NameFr;
            }
            set
            {
                this.OnNameFrChanging(value);
                this._NameFr = value;
                this.OnNameFrChanged();
                this.OnPropertyChanged("NameFr");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NameFr;
        partial void OnNameFrChanging(string value);
        partial void OnNameFrChanged();
        /// <summary>
        /// There are no comments for Property NameEs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NameEs
        {
            get
            {
                return this._NameEs;
            }
            set
            {
                this.OnNameEsChanging(value);
                this._NameEs = value;
                this.OnNameEsChanged();
                this.OnPropertyChanged("NameEs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NameEs;
        partial void OnNameEsChanging(string value);
        partial void OnNameEsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
