//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 22/01/2015 21:39:09
namespace TermsCrm.TermsServiceReference
{
    
    /// <summary>
    /// There are no comments for asbMeetingEntities in the schema.
    /// </summary>
    public partial class asbMeetingEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new asbMeetingEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public asbMeetingEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "asbMeetingModel", "TermsCrm.TermsServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TermsCrm.TermsServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("asbMeetingModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Conferences in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Conferences> Conferences
        {
            get
            {
                if ((this._Conferences == null))
                {
                    this._Conferences = base.CreateQuery<Conferences>("Conferences");
                }
                return this._Conferences;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Conferences> _Conferences;
        /// <summary>
        /// There are no comments for Terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Terms> Terms
        {
            get
            {
                if ((this._Terms == null))
                {
                    this._Terms = base.CreateQuery<Terms>("Terms");
                }
                return this._Terms;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Terms> _Terms;
        /// <summary>
        /// There are no comments for Conferences in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToConferences(Conferences conferences)
        {
            base.AddObject("Conferences", conferences);
        }
        /// <summary>
        /// There are no comments for Terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTerms(Terms terms)
        {
            base.AddObject("Terms", terms);
        }
    }
    /// <summary>
    /// There are no comments for asbMeetingModel.Conferences in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Conferences")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Conferences : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Conferences object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Conferences CreateConferences(global::System.Guid ID)
        {
            Conferences conferences = new Conferences();
            conferences.id = ID;
            return conferences;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this._title = value;
                this.OntitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this._start = value;
                this.OnstartChanged();
                this.OnPropertyChanged("start");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _start;
        partial void OnstartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this._end = value;
                this.OnendChanged();
                this.OnPropertyChanged("end");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
        /// <summary>
        /// There are no comments for Property kind in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string kind
        {
            get
            {
                return this._kind;
            }
            set
            {
                this.OnkindChanging(value);
                this._kind = value;
                this.OnkindChanged();
                this.OnPropertyChanged("kind");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _kind;
        partial void OnkindChanging(string value);
        partial void OnkindChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property access in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string access
        {
            get
            {
                return this._access;
            }
            set
            {
                this.OnaccessChanging(value);
                this._access = value;
                this.OnaccessChanged();
                this.OnPropertyChanged("access");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _access;
        partial void OnaccessChanging(string value);
        partial void OnaccessChanged();
        /// <summary>
        /// There are no comments for Property status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this._status = value;
                this.OnstatusChanged();
                this.OnPropertyChanged("status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status;
        partial void OnstatusChanging(string value);
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for Property imageUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageUrl
        {
            get
            {
                return this._imageUrl;
            }
            set
            {
                this.OnimageUrlChanging(value);
                this._imageUrl = value;
                this.OnimageUrlChanged();
                this.OnPropertyChanged("imageUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageUrl;
        partial void OnimageUrlChanging(string value);
        partial void OnimageUrlChanged();
        /// <summary>
        /// There are no comments for Property imageCopyright in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageCopyright
        {
            get
            {
                return this._imageCopyright;
            }
            set
            {
                this.OnimageCopyrightChanging(value);
                this._imageCopyright = value;
                this.OnimageCopyrightChanged();
                this.OnPropertyChanged("imageCopyright");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageCopyright;
        partial void OnimageCopyrightChanging(string value);
        partial void OnimageCopyrightChanged();
        /// <summary>
        /// There are no comments for Property location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this.OnlocationChanging(value);
                this._location = value;
                this.OnlocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _location;
        partial void OnlocationChanging(string value);
        partial void OnlocationChanged();
        /// <summary>
        /// There are no comments for Property city in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                this.OncityChanging(value);
                this._city = value;
                this.OncityChanged();
                this.OnPropertyChanged("city");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _city;
        partial void OncityChanging(string value);
        partial void OncityChanged();
        /// <summary>
        /// There are no comments for Property country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string country
        {
            get
            {
                return this._country;
            }
            set
            {
                this.OncountryChanging(value);
                this._country = value;
                this.OncountryChanged();
                this.OnPropertyChanged("country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _country;
        partial void OncountryChanging(string value);
        partial void OncountryChanged();
        /// <summary>
        /// There are no comments for Property updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> updated
        {
            get
            {
                return this._updated;
            }
            set
            {
                this.OnupdatedChanging(value);
                this._updated = value;
                this.OnupdatedChanged();
                this.OnPropertyChanged("updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _updated;
        partial void OnupdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnupdatedChanged();
        /// <summary>
        /// There are no comments for Property brs_country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_country
        {
            get
            {
                return this._brs_country;
            }
            set
            {
                this.Onbrs_countryChanging(value);
                this._brs_country = value;
                this.Onbrs_countryChanged();
                this.OnPropertyChanged("brs_country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_country;
        partial void Onbrs_countryChanging(string value);
        partial void Onbrs_countryChanged();
        /// <summary>
        /// There are no comments for Property brs_unregion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_unregion
        {
            get
            {
                return this._brs_unregion;
            }
            set
            {
                this.Onbrs_unregionChanging(value);
                this._brs_unregion = value;
                this.Onbrs_unregionChanged();
                this.OnPropertyChanged("brs_unregion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_unregion;
        partial void Onbrs_unregionChanging(string value);
        partial void Onbrs_unregionChanged();
        /// <summary>
        /// There are no comments for Property brs_treaties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_treaties
        {
            get
            {
                return this._brs_treaties;
            }
            set
            {
                this.Onbrs_treatiesChanging(value);
                this._brs_treaties = value;
                this.Onbrs_treatiesChanged();
                this.OnPropertyChanged("brs_treaties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_treaties;
        partial void Onbrs_treatiesChanging(string value);
        partial void Onbrs_treatiesChanged();
        /// <summary>
        /// There are no comments for Property brs_terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_terms
        {
            get
            {
                return this._brs_terms;
            }
            set
            {
                this.Onbrs_termsChanging(value);
                this._brs_terms = value;
                this.Onbrs_termsChanged();
                this.OnPropertyChanged("brs_terms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_terms;
        partial void Onbrs_termsChanging(string value);
        partial void Onbrs_termsChanged();
        /// <summary>
        /// There are no comments for Property brs_SessionLanguage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> brs_SessionLanguage
        {
            get
            {
                return this._brs_SessionLanguage;
            }
            set
            {
                this.Onbrs_SessionLanguageChanging(value);
                this._brs_SessionLanguage = value;
                this.Onbrs_SessionLanguageChanged();
                this.OnPropertyChanged("brs_SessionLanguage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _brs_SessionLanguage;
        partial void Onbrs_SessionLanguageChanging(global::System.Nullable<int> value);
        partial void Onbrs_SessionLanguageChanged();
        /// <summary>
        /// There are no comments for Property brs_LinkRegistration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_LinkRegistration
        {
            get
            {
                return this._brs_LinkRegistration;
            }
            set
            {
                this.Onbrs_LinkRegistrationChanging(value);
                this._brs_LinkRegistration = value;
                this.Onbrs_LinkRegistrationChanged();
                this.OnPropertyChanged("brs_LinkRegistration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_LinkRegistration;
        partial void Onbrs_LinkRegistrationChanging(string value);
        partial void Onbrs_LinkRegistrationChanged();
        /// <summary>
        /// There are no comments for Property brs_LinkFaq in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_LinkFaq
        {
            get
            {
                return this._brs_LinkFaq;
            }
            set
            {
                this.Onbrs_LinkFaqChanging(value);
                this._brs_LinkFaq = value;
                this.Onbrs_LinkFaqChanged();
                this.OnPropertyChanged("brs_LinkFaq");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_LinkFaq;
        partial void Onbrs_LinkFaqChanging(string value);
        partial void Onbrs_LinkFaqChanged();
        /// <summary>
        /// There are no comments for Property brs_LinkRecording in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_LinkRecording
        {
            get
            {
                return this._brs_LinkRecording;
            }
            set
            {
                this.Onbrs_LinkRecordingChanging(value);
                this._brs_LinkRecording = value;
                this.Onbrs_LinkRecordingChanged();
                this.OnPropertyChanged("brs_LinkRecording");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_LinkRecording;
        partial void Onbrs_LinkRecordingChanging(string value);
        partial void Onbrs_LinkRecordingChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for asbMeetingModel.Terms in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TermId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Terms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TermId")]
    public partial class Terms : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Terms object.
        /// </summary>
        /// <param name="termId">Initial value of TermId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Terms CreateTerms(global::System.Guid termId)
        {
            Terms terms = new Terms();
            terms.TermId = termId;
            return terms;
        }
        /// <summary>
        /// There are no comments for Property TermId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid TermId
        {
            get
            {
                return this._TermId;
            }
            set
            {
                this.OnTermIdChanging(value);
                this._TermId = value;
                this.OnTermIdChanged();
                this.OnPropertyChanged("TermId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _TermId;
        partial void OnTermIdChanging(global::System.Guid value);
        partial void OnTermIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Synonyms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Synonyms
        {
            get
            {
                return this._Synonyms;
            }
            set
            {
                this.OnSynonymsChanging(value);
                this._Synonyms = value;
                this.OnSynonymsChanged();
                this.OnPropertyChanged("Synonyms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Synonyms;
        partial void OnSynonymsChanging(string value);
        partial void OnSynonymsChanged();
        /// <summary>
        /// There are no comments for Property InformeaTerm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InformeaTerm
        {
            get
            {
                return this._InformeaTerm;
            }
            set
            {
                this.OnInformeaTermChanging(value);
                this._InformeaTerm = value;
                this.OnInformeaTermChanged();
                this.OnPropertyChanged("InformeaTerm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InformeaTerm;
        partial void OnInformeaTermChanging(string value);
        partial void OnInformeaTermChanged();
        /// <summary>
        /// There are no comments for Property ParentTermNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ParentTermNames
        {
            get
            {
                return this._ParentTermNames;
            }
            set
            {
                this.OnParentTermNamesChanging(value);
                this._ParentTermNames = value;
                this.OnParentTermNamesChanged();
                this.OnPropertyChanged("ParentTermNames");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ParentTermNames;
        partial void OnParentTermNamesChanging(string value);
        partial void OnParentTermNamesChanged();
        /// <summary>
        /// There are no comments for Property ParentTermIds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ParentTermIds
        {
            get
            {
                return this._ParentTermIds;
            }
            set
            {
                this.OnParentTermIdsChanging(value);
                this._ParentTermIds = value;
                this.OnParentTermIdsChanged();
                this.OnPropertyChanged("ParentTermIds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ParentTermIds;
        partial void OnParentTermIdsChanging(string value);
        partial void OnParentTermIdsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
